version: "3.3"
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
    environment:
      DB_HOST: db
      DB_NAME: ${APP_DB_NAME}
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
      MYSQL_ALLOW_EMOTY_PASSWORD: 'yes'
